const currentlyReadingList = [
  "A Good Day To Pitch A Tent",
  "A Pervert's Daily life",
  "A Rich Lady",
  "A Sweet Part Time Job",
  "A Twisted Day",
  "A Wise Driver's Life",
  "A Wonderful New World",
  "Addicted to My Stepmom",
  "Aharoo",
  "An Alley story",
  "Bad Thinking Diary",
  "Banging My Aunt",
  "Barefoot : The Leash Season 2",
  "Bastard",
  "Bastard’s Dead Man",
  "Between Us",
  "Big Boss Gone Bad",
  "Block 69",
  "Boarding Diary",
  "Body Bind",
  "Boobie Trap",
  "Bought By The Demon Lord Before The Ending",
  "Breakaway : Joys of Travel",
  "Bully Girl",
  "Bunk Beds",
  "Campus Live",
  "Childhood Bride",
  "Circles",
  "Close Family",
  "Club Sodom",
  "College Secrets",
  "Concubine",
  "Could You Please Touch Me There?",
  "Cucumber Market",
  "Daddy’s Wild Oats",
  "Dance Department's Female Sunbaes",
  "Department Store Ladies",
  "Desire Realization App",
  "Difficult Choices",
  "Dirty Reverie",
  "Do It One More Time",
  "Dorm Room Sisters",
  "Elf Who Likes To Be Humiliated",
  "Everything Is Agreed",
  "Everything about Best Friend",
  "Falling for her",
  "Family Adjustments",
  "Family Secret",
  "Fatal Woman",
  "Father's Lust",
  "Floor Noise",
  "Forcing the Woman I Despise Into Submission",
  "Frequency",
  "Freshman",
  "Friend’s Girlfriend",
  "Girls I Used to Teach",
  "Go Ahead, Mom",
  "God Model",
  "Goddess Hunting",
  "Heart Stealer",
  "Heaven",
  "His Place",
  "Honestly, I like you a lot!",
  "Housekeeper",
  "How About This Pose?",
  "Hunting for Cougars",
  "Hyeonjung’s Residence",
  "I Can’t Stand It, Ajumma",
  "Ice Love",
  "In Her Place",
  "In The Summer",
  "Intern Haenyeo",
  "Is It Your Mother or Sister?",
  "Is there an Empty Room?",
  "It’s Okay Because We’re Family",
  "I’ll Eat Your Mom First",
  "Just Right There!",
  "Keep it a secret from your mother!",
  "Kitsch Year",
  "Ladies’ Man",
  "Law Of Reincarnation",
  "Learning The Hard Way",
  "Let's Hang Out from Today",
  "Let Me Drive",
  "Lightning Rod",
  "Lilith’s Cord",
  "Live With : Do You Want To Do It?",
  "Live-In Son-in-Law",
  "Living With Two Busty Women",
  "Living With a MILF",
  "Locked Up",
  "Love Limit Exceeded",
  "Lucky Guy",
  "Lust Awakening",
  "MAD : Escort Driver",
  "MILF Hunting In Another World",
  "Madam",
  "Magnetic Pull",
  "Man of The House",
  "Marriage Agency Review",
  "May I Help you?",
  "Midnight Taxi",
  "Moby Dick",
  "Modern Apartment, Gyeonseong 1930",
  "Mother-In-Law Bends to My Will",
  "Mother-Son Island Survival",
  "My Father’s USB",
  "My First and Last",
  "My Landlady Noona",
  "My Memory of You",
  "My Sister-in-law’s Skirt",
  "My Sister’s Friends",
  "My Wife’s Friend",
  "My female friend who crossed the line",
  "Naughty Girl",
  "New Town",
  "Not at Work",
  "Not in School!",
  "Not to be missed",
  "Only You",
  "Panty Note",
  "Paradise Lost",
  "Park Moojik Hit the Jackpot",
  "Peek",
  "Perfect Half",
  "Pheromone",
  "Please Scan Here",
  "Pulse",
  "Queen Bee",
  "Resume",
  "Revenge",
  "Roomie",
  "Roommates with benefits",
  "Sahwa: Secret Commission",
  "Salamander",
  "Secret Class",
  "Secret Cohabitation",
  "Serenade",
  "Sexercise",
  "Sexy Man and Woman",
  "Shall We Ride?",
  "Sharing is Caring",
  "Should I Study at Noryangjin?",
  "Show Me Your Color",
  "Siblings",
  "Simple yet Sexy",
  "Siren (Getty)",
  "Sister in Law",
  "Sneaky Deal",
  "So close, yet so far",
  "Son of Nam",
  "Soothe Me",
  "Staying with Ajumma",
  "Stepsister",
  "Succubus System",
  "Supervisor Access",
  "Sweet Family",
  "Taiyo’s Sisters-In-Law Need His Seed",
  "Taming a Maid",
  "Teacher’s Pet",
  "The Cheat Code Hitter Fucks Them All",
  "The Commander’s Daughter",
  "The Desperate Housewife",
  "The Escape",
  "The Four Of Us Can't Live Together",
  "The Girl Next Door",
  "The Hole Diary",
  "The Hole is Open",
  "The Hypnosis App was Fake",
  "The Mismatch",
  "The Neighborhood Celebrity",
  "The Real Deal",
  "The Runaway Family",
  "The Secret Affairs Of The 3rd Generation Chaebol",
  "The Share House's Secret Rule",
  "The Sharehouse",
  "The Story of How I Got Together With The Manager On Christmas",
  "The Third Party",
  "The Unwanted Roommate",
  "Thorns of Innocence",
  "Tonight, You’re My Dinner",
  "Touch to Unlock",
  "Turned On By My Nephew",
  "Tutoring the Lonely Missus",
  "Twin Takes",
  "Under the Radar",
  "Understanding of Flirting",
  "Wait, I’m a Married Woman!",
  "Wanna live by the countryside?",
  "Welcome to Kids Cafe",
  "What Do I Do Now?",
  "What Do You Take Me For?",
  "What’s for Dinner",
  "What’s for Today Dinner?",
  "When Did We Start Dating?!",
  "Where is My Hammer?",
  "White Angels Have No Wings",
  "Wreck My Bias",
  "Young Boss",
  "Young Housemaid",
  "Your Wife Was Amazing",
].map(standardiseString);
