const currentlyReadingList = [
  "24 Hour Love",
  "A Good Day To Pitch A Tent",
  "A Guide to Corrupting Them With Hypnosis",
  "A Guy and a Girl Stuck in an Elevator",
  "A Pervert's Daily life",
  "A Rich Lady",
  "A Stolen Taste",
  "A Sweet Part Time Job",
  "A Wise Driver's Life",
  "A Wonderful New World",
  "Absolute Hypnosis in Another World",
  "Addicted to My Stepmom",
  "Amazing Reincarnation",
  "An Alley story",
  "As If Daughter",
  "Bad Guy",
  "Bad Thinking Diary",
  "Barefoot : The Leash Season 2",
  "Bastard",
  "Beach Goddess",
  "Beautiful Days",
  "Beethoven Syndrome",
  "Benefactor's Daughters",
  "Big Boss Gone Bad",
  "Boarding Diary",
  "Boobie Trap",
  "Bought By The Demon Lord Before The Ending",
  "Breakaway : Joys of Travel",
  "Breaking A Romantic Fantasy Villain",
  "Brother's Wife Dignity",
  "Bunk Beds",
  "Cabin Resort X",
  "Campus Live",
  "Campus Today",
  "Cheer Up, Brother In Law",
  "Chicken Club",
  "Childhood Bride",
  "Childhood Friend of the Zenith",
  "Circles",
  "College Secrets",
  "Concubine",
  "Could You Please Touch Me There?",
  "Craving",
  "Cucumber Market",
  "Daddy’s Wild Oats",
  "Dance Department's Female Sunbaes",
  "Delivery",
  "Delusional Diary",
  "Department Store Ladies",
  "Difficult Choices",
  "Disciplining the Top Delinquent Bitch Through a Random Chatting App",
  "Distractions",
  "Do It One More Time",
  "Dog on Patrol",
  "Downstairs Lady",
  "Driver in the New City",
  "Drunk on You",
  "Elf Who Likes To Be Humiliated",
  "Eunha’s Advice",
  "Everything Is Agreed",
  "Falling for her",
  "Family Adjustments",
  "Family Secret",
  "Family with Benefits",
  "Father's Lust",
  "First time with my wife (again)",
  "Floor Noise",
  "Forcing the Woman I Despise Into Submission",
  "Freshman",
  "Friend's Mom Is Mine",
  "Friends with Secrets",
  "Friend’s Girlfriend",
  "Gangnam Romance",
  "Gangster x Office Lady",
  "Girls I Used to Teach",
  "Go Ahead, Mom",
  "God Bless You",
  "God Model",
  "God of Pleasure",
  "Goddess Hunting",
  "Golden Facade",
  "Grand Disciple",
  "Greed Game",
  "Heart Stealer",
  "Heaven",
  "Hell's Harem",
  "Her 4 Incher",
  "Her Toy Shop",
  "His Place",
  "Honestly, I like you a lot!",
  "House of Pleasure",
  "How About This Pose?",
  "I Became The Sex Art Master In My Murim Novel",
  "I Became a Pornhwa NPC",
  "Ice Love",
  "Idiot Virus",
  "In Her Place",
  "In The Summer",
  "Is It Your Mother or Sister?",
  "Is there an Empty Room?",
  "It’s Okay Because We’re Family",
  "I’ll Eat Your Mom First",
  "Just For You",
  "Just Right There!",
  "Kitsch Year",
  "Ladies’ Man",
  "Land of the Dead",
  "Learning The Hard Way",
  "Let Me Drive",
  "Let's Hang Out from Today",
  "Lightning Rod",
  "Like No Other",
  "Lilith’s Cord",
  "Live With : Do You Want To Do It?",
  "Locked Up",
  "Love Choice",
  "Love Gacha",
  "Love Limit Exceeded",
  "Lucky Guy",
  "Lust Awakening",
  "Lustful Woman",
  "MAD : Escort Driver",
  "Madam",
  "Maid Rehabilitation",
  "Making It in a Comic Book World",
  "Man of The House",
  "Manager",
  "Marriage Agency Review",
  "May I Help you?",
  "Milf Guard",
  "Mind Reader",
  "Moby Dick",
  "Modern Apartment, Gyeonseong 1930",
  "My Aunt in Puberty",
  "My Baby Girl",
  "My Brother's Slipped Inside Me in The Bathtub",
  "My Eyes Now See Desire",
  "My First and Last",
  "My Love Companion",
  "My Memory of You",
  "My New Family Treats me Well",
  "My Sister-in-law’s Skirt",
  "My Sister’s Friends",
  "My Stowaway Diary",
  "My Students Who Became Parents",
  "Night With My Sister",
  "Nightmare",
  "Not Safe for Work ♡",
  "Not at Work",
  "Not the Daughter, but the Mother",
  "Not to be missed",
  "Obsessive Romance",
  "Office Desires",
  "Office Shitbag Alert",
  "Oppa, Not There",
  "Origin of Sensibility",
  "Paradise Lost",
  "Pay with Sperm Pay",
  "Peek",
  "Perfect Half",
  "Pervert Diary",
  "Pet's Aesthetics",
  "Pheromone",
  "Please Scan Here",
  "Pleasure up!",
  "Principles and Practices of Lovemaking",
  "Pulse",
  "Queen Bee",
  "Reborn with a big dick!",
  "Regressed Warrior's Female Dominance",
  "Resume",
  "Revenge",
  "Ripley Love",
  "Rise and Shine, Hero!",
  "Roomie",
  "Roommates with benefits",
  "S Class",
  "Sahwa: Secret Commission",
  "Salamander",
  "Say You Like It",
  "Secret Class",
  "Secret Cohabitation",
  "Secret Education with My Lady",
  "Secret Office",
  "Secret Siblings",
  "Secret Tutor",
  "Serenade",
  "Sex Lottery",
  "Sexercise",
  "Sextudy Group",
  "Sexual Exploits",
  "Sexy Man and Woman",
  "Shall We Ride?",
  "Sharing is Caring",
  "She is Working Out",
  "She's my Younger Sister, but it's okay",
  "Should I Study at Noryangjin?",
  "Show Me Your Color",
  "Simple yet Sexy",
  "Siren (Getty)",
  "Sister in Law",
  "Sister’s Sex Education",
  "Smart App Life",
  "Someone Stop Her!",
  "Soothe Me",
  "Staying with Ajumma",
  "Stepsister",
  "Summer Vacation",
  "Supervisor Access",
  "Sweet Family",
  "Sweet Holiday",
  "Swim in the Cherry",
  "Taiyo’s Sisters-In-Law Need His Seed",
  "Taming a Maid",
  "Taste of Forbbiden Fruit",
  "Tax Girlfriend",
  "Teach Me How to Please You",
  "Teacher Punishment",
  "Teacher’s Pet",
  "Team Leader Report",
  "The Billionaire’s Monster Cock Son-In-Law",
  "The Boss’s Daughter",
  "The Chairman's Wife",
  "The Desperate Housewife",
  "The Escape",
  "The Four Of Us Can't Live Together",
  "The Girl Hiding in the Wall",
  "The Girlfriend Dice",
  "The Girls I couldn't date before",
  "The Hole is Open",
  "The Housemaid",
  "The Hypnosis App was Fake",
  "The Intentions of the Neighborhood Meeting",
  "The Lustful Demon is the King of Demons",
  "The Mismatch",
  "The Regressed Son of a Duke is an Assassin",
  "The Runaway Family",
  "The Servant’s Story",
  "The Share House's Secret Rule",
  "The Sharehouse",
  "The Teachers’ Efforts",
  "The Third Party",
  "The Turning Point",
  "The Woman Who Lives In My Room",
  "Thorns of Innocence",
  "Three Sisters",
  "Top Of The World",
  "Touch to Unlock",
  "Turned On By My Nephew",
  "Twenty",
  "Twin Takes",
  "Under the Radar",
  "Understanding of Flirting",
  "Unlocking her",
  "Wait, I’m a Married Woman!",
  "Wanna Become a Dad or a Boyfriend?",
  "Wanna live by the countryside?",
  "Water Overflow",
  "What Do I Do Now?",
  "What Do You Take Me For?",
  "What's wrong with this family?",
  "When Did We Start Dating?!",
  "White Angels Have No Wings",
  "Women's University Student who Served in the Military",
  "Wreck My Bias",
  "You Are My First",
  "Young Aunt",
  "Young Housemaid",
  "Your Girlfriend Was Amazing",
  "Your Wife Was Amazing",
].map(standardiseString);
