const readOrIgnoreWebtoons = [
  "#Dense #Summer #Firstlove",
  "15 Beauties",
  "15 Minutes",
  "150-1 Street",
  "A Chaste Girl’s Climax at a Nudist Beach",
  "A Different Class",
  "A Killer Woman",
  "A Secret Lesson With My Younger Sister",
  "A Twisted Day",
  "A World That I Rule",
  "A World of Our Own",
  "Achilles Heel",
  "Aesthetic Predator",
  "Alive and Swell",
  "Amnesia",
  "An Adult’s Experiences",
  "An Innocent Sin",
  "Analogue",
  "Anything for You",
  "Aqua",
  "BROTHEL",
  "Back with a Bang",
  "Bad Mom",
  "Bad Parenting",
  "Banging Mother And Daughter",
  "Banging My Aunt",
  "Be Our Guest",
  "Between Us (Goinmul)",
  "Beyond Imagination",
  "Billiard Room Love",
  "Block 69",
  "Blood Link",
  "Blooming Sequence",
  "Body Bind",
  "Boss Around",
  "Brawling Go!",
  "Bride Training",
  "Bully Girl",
  "Busted in One Thrust",
  "Butterfly Dream",
  "By Chance",
  "Caffeine",
  "Campus Love",
  "Capture",
  "Cartoonists NSFW",
  "Casting",
  "Castle ; Trapped",
  "Cat Fight",
  "Change Wife",
  "Cheater’s Paradise",
  "Cheer Up, Namjoo",
  "Close As Neighbors",
  "Close Family",
  "Cohabitation with my Ex-Wife",
  "Cohabitation!",
  "Collapse & Rewind",
  "Corner Shop",
  "Couple Game: 17 Sex Fantasies Ver.2",
  "Cowgirl’s Riding-Position Makes Me Cum",
  "Creampie",
  "Crime And Punishment",
  "DISFARMING",
  "Daddy-in-law",
  "Dangerous Roomies",
  "Dating Contract",
  "Daughter Friend",
  "Daughter In Law",
  "Daydream",
  "Dear Door",
  "Death Angel",
  "Deceit: Snake’s Tongue",
  "Deceptions",
  "Depths of Hell",
  "Desire Realization App",
  "Desperate Measures",
  "Deviant Diary",
  "Dirty Reverie",
  "Don’t Be Like This! Son-In-Law",
  "Don’t Seduce Me!",
  "Dorm Room Sisters",
  "Double Life of Gukbap",
  "Drama in the Office",
  "Dreaming : My Friend’s Girl",
  "Drug Candy",
  "Drunk and Wet",
  "Dual Residence",
  "Dumped",
  "E Romance",
  "Ecstasy Hearts",
  "Elixir",
  "Emergency Stairs",
  "Everyday Lily",
  "Everything about Best Friend",
  "Ex-girlfriend",
  "Exclusive Contract",
  "Excuse me, This is my Room",
  "Extra Credit",
  "Fallen Flower",
  "Family Business",
  "Fatal Woman",
  "Festival Island",
  "Find Me",
  "Flames",
  "Food Chain",
  "Friendly Relationship",
  "From Poker Face to Cumming Face in 90 Seconds",
  "Front House Lily",
  "Fruitless",
  "Fucked the World Tree",
  "Getting to Know Grace",
  "Ghost Love",
  "Girls’ Only",
  "Gluestick Girl",
  "God of App",
  "Gu-Ho’s Escape",
  "Guest House",
  "H-Campus",
  "H-Mate",
  "Hadomae",
  "Hand Play",
  "Hand in Hand",
  "Happy",
  "Healing Hands OBGYN",
  "Her Dirty Thirty Scandal",
  "Her Situation",
  "Her Voice",
  "Herbal Love Story",
  "Hidden Feeling",
  "Him and Him and Him",
  "His Return",
  "Hole in One",
  "Homestay",
  "Honey Bed Talk",
  "Hooked",
  "Household Affairs",
  "Housekeeper",
  "How to Train Her",
  "Hugo",
  "Hyeonjung's Residence",
  "I Can’t Stand It, Ajumma",
  "I Gave My First Time to My Brother",
  "I Have To Sleep With A Stranger?",
  "Illicit Love",
  "Isekai Fall of the Hero",
  "Inside the Uniform",
  "Inside the bus",
  "Island Puzzle",
  "Johnson Contract",
  "Keep it a secret from your mother!",
  "Killing Stalking",
  "Kitsch Year",
  "Lady & Maid",
  "Lady Elisha’s Diary of Debauchery",
  "Lady Garden",
  "Lady Long Legs",
  "Law Of Reincarnation",
  "Leave the Work to Me!",
  "Lesbian Sex Hell",
  "Let it be",
  "Live-In Son-in-Law",
  "Living With a MILF",
  "Living with A Succubus",
  "Living With Two Busty Women",
  "Log in to Lust-a-land",
  "Love Factory",
  "Love Is On The Air",
  "Love Me More",
  "Love Prelude",
  "What’s for Dinner",
  "What’s for Today Dinner?",
  "Tonight, You’re My Dinner",
  "Love Parameter",
  "Loveniverse",
  "Ma'am, it's on SALE!",
  "Magnetic Pull",
  "Maid",
  "Make a Wish",
  "Making My Blackmailer Cum",
  "Malja",
  "Mamitas",
  "Married Woman",
  "Masters of Masturbation",
  "Mean Guy",
  "Mia’s Tool",
  "Midnight Breeze",
  "Midnight Taxi",
  "Midsummer Night’s Dream",
  "Miss Mystic",
  "Missing Nine",
  "More Than Friends",
  "Mother And Daughter Next Door",
  "Mother Hunting",
  "Mother-In-Law Bends to My Will",
  "Mother-Son Island Survival",
  "Ms. Master (Aunt’s Secret)",
  "Ms.Stepford",
  "My Aunt in Puberty",
  "My Aunt",
  "My Best Friend’s Girl",
  "My Body",
  "My Dad’s Girl",
  "My Father’s USB",
  "My First Time is with... My Little Sister!?",
  "My Friend’s Dad",
  "My Friend’s Sister",
  "My Girlfriend is My Stepmother",
  "My Kingdom (Silent War)",
  "My Neighborhood’s Female Teacher",
  "My Secretary’s Got a Secret",
  "My Stepmom",
  "My Stepmom’s Plan",
  "My Teacher",
  "My Wife is a Mom",
  "My Wife’s Friend",
  "My Wives",
  "My Worst Lover",
  "My female friend who crossed the line",
  "My girlfriend is a G-Cup!",
  "NEXT Gossip",
  "Naughty Positions",
  "Never Too Late",
  "New Employee",
  "New Town",
  "Nineteen",
  "No Goddess, No!",
  "No Holes Barred",
  "No Way Out",
  "Nogada Romance",
  "Not Friends",
  "Not One, But Two",
  "Not Safe for Work ♡",
  "Not in School!",
  "Obscene Baguette",
  "Office Ladies",
  "On My Way",
  "One's In-Laws Virgins",
  "Only You",
  "Our Complications",
  "Our Exchange",
  "Overlapping",
  "Panties Fantasy",
  "Part Time Job",
  "Payment Accepted",
  "Pet Robot Lilly",
  "Please Kill My Husband",
  "Pleasure Chamber",
  "Polyamory",
  "Pregnancy Village",
  "Prison Island",
  "Public Interest",
  "Punishments for Bad Girls",
  "Rabbit Hole",
  "Raw Sex With a Country Gal ~I’ll Show You the Ropes~",
  "Refrain Love",
  "Reporting For Duty Ma’Am",
  "Returning Girlfriend",
  "Risque Caller",
  "Run Away",
  "S Flower",
  "SEDUCTION : Doll Castle",
  "SStudy",
  "Sadistic Beauty",
  "Safe Haven",
  "Secret Alliance",
  "Secret Campus",
  "Secret Friend",
  "Secret Neighbors",
  "Secret X Folder",
  "Seeing Her Panties Lets Me Stick In",
  "Sergeant Brynn",
  "Sex Knights",
  "Sex Stopwatch",
  "Sexy Manga Club",
  "Sexy Virtual Elf",
  "She Is Young",
  "She’s Back",
  "Shh! Her Secret",
  "Shorts",
  "Si-Eun",
  "Single Again",
  "Sister In Law (Kim Jol Gu)",
  "Sister-in-law",
  "Slave Knight of the Elf",
  "Sneaked Into A Horny Girls’ School",
  "Sneaky Deal",
  "So close, yet so far",
  "Sold Out Girl",
  "Son of Nam",
  "Sow",
  "Spirit Possession",
  "Sports Girl",
  "Stand up Guy",
  "Stargram Goddess",
  "Stepmother Friends",
  "Stolen",
  "Stuck in Time",
  "Study Dates",
  "Stupid Love",
  "Succubus System",
  "Sweet Angels",
  "Sweet Guy",
  "Talk to Me",
  "Tasty Chat 0km",
  "Teacher Training",
  "Tell Me You Love Me",
  "The Assistant",
  "The Blood of Madam Giselle",
  "THE CHANGE OF SEASON",
  "The Cheat Code Hitter Fucks Them All",
  "The Commander's Daughter",
  "The Delivery Man",
  "The Desire to Kill",
  "The Duchess’ Lewd Invitation",
  "The Family Tree",
  "The Fling Zone",
  "The Food Chain",
  "The Girl Next Door",
  "The Girl that Wet the Wall",
  "The Good Manager",
  "The Ladies’ Associate",
  "The Mask: Two Faces",
  "The Men in My Bed",
  "The Naughty Volleyball Team",
  "The Neighborhood Celebrity",
  "The Paradise",
  "The Perfect Roommates",
  "The Real Deal",
  "The Repeat Student",
  "The Secret 3P Sleepover in a 7 Square Meter Room",
  "The Secret Affairs Of The 3rd Generation Chaebol",
  "The Sexy Alien Next Door",
  "The Show",
  "The Snow",
  "The Stand-up Guy",
  "The Story of How I Got Together With The Manager On Christmas",
  "The Taste of Money",
  "The Two Newcomers",
  "The Unforeseen Guest",
  "The Unwanted Roommate",
  "The Whale",
  "The White Room",
  "The Widow",
  "Thirst",
  "Thirty-two VS Twenty",
  "Tie Me Up!",
  "Tonight",
  "Tonight, You're My Dinner",
  "Touch Me",
  "Touching My Older Sister Under the Table",
  "Trophy Wives",
  "Troublesome Sister",
  "Twice the Love",
  "Twin Recipe",
  "Two Birds In Spring",
  "Two Wives",
  "Uncle",
  "Under Observation My First Loves and I",
  "Unspeakable",
  "Venus Guytrap",
  "WIFE GAME",
  "Weak Point",
  "Welcome to Kids Cafe",
  "What Does the Fox Say?",
  "What’s Going On?",
  "Where is My Hammer?",
  "Who Cares If I’m a Loser!",
  "Who Did You Do With?",
  "Why Is it You?",
  "Wife Training",
  "Wild Eyes",
  "Will You Do as I Say?",
  "With My Brother’s Friends",
  "Woodman Dyeon",
  "You Can Cum Three More Times, Right?",
  "You Me Her",
  "You are not that Special!",
  "You’re so Handsome",
  "gomusin",
  "“Hypnotized” Sex with My Brother",
  "“Just The Tip Inside” is Not Sex",
].map(standardiseString);
