const readOrIgnoreWebtoons = [
  "#Dense #Summer #Firstlove",
  "15 Beauties",
  "15 Minutes",
  "150-1 Street",
  "A Chaste Girl’s Climax at a Nudist Beach",
  "A Different Class",
  "A Killer Woman",
  "A Secret Lesson With My Younger Sister",
  "A Twisted Day",
  "A World That I Rule",
  "A World of Our Own",
  "A Young Auntie",
  "AMU",
  "Achilles Heel",
  "Aesthetic Predator",
  "Alive and Swell",
  "Alt Account Trap!",
  "Amnesia",
  "An Adult’s Experiences",
  "An Innocent Sin",
  "Analogue",
  "Anything for You",
  "Aqua",
  "BROTHEL",
  "Back with a Bang",
  "Bad Mom",
  "Bad Parenting",
  "Banging Mother And Daughter",
  "Banging My Aunt",
  "Bastard’s Dead Man",
  "Be Our Guest",
  "Between Us (Goinmul)",
  "Between Us",
  "Beyond Imagination",
  "Billiard Room Love",
  "Blazing Sun",
  "Block 69",
  "Blood Link",
  "Blooming Sequence",
  "Body Bind",
  "Body Choke",
  "Boss Around",
  "Boss Reverse",
  "Brawling Go!",
  "Bride Training",
  "Bully Girl",
  "Busted in One Thrust",
  "Butterfly Dream",
  "By Chance",
  "Caffeine",
  "Campus Love",
  "Capture",
  "Cartoonists NSFW",
  "Casting",
  "Castle ; Trapped",
  "Cat Fight",
  "Change Wife",
  "Cheater’s Paradise",
  "Cheer Up, Namjoo",
  "Close As Neighbors",
  "Close Family",
  "Club Sodom",
  "Cohabitation with my Ex-Wife",
  "Cohabitation!",
  "Collapse & Rewind",
  "Corner Shop",
  "Couple Game: 17 Sex Fantasies Ver.2",
  "Cowgirl’s Riding-Position Makes Me Cum",
  "Creampie",
  "Crime And Punishment",
  "Crossing the Line",
  "DISFARMING",
  "Daddy-in-law",
  "Dangerous Roomies",
  "Dating Contract",
  "Daughter Friend",
  "Daughter In Law",
  "Daydream",
  "Dear Door",
  "Death Angel",
  "Deceit: Snake’s Tongue",
  "Deceptions",
  "Depths of Hell",
  "Desire Realization App",
  "Desperate Measures",
  "Deviant Diary",
  "Dirty Reverie",
  "Don’t Be Like This! Son-In-Law",
  "Don’t Seduce Me!",
  "Dorm Room Sisters",
  "Double Life of Gukbap",
  "Double Trouble",
  "Drama in the Office",
  "Dreaming : My Friend’s Girl",
  "Drug Candy",
  "Drunk and Wet",
  "Dual Residence",
  "Dumped",
  "E Romance",
  "Ecstasy Hearts",
  "Elixir",
  "Emergency Stairs",
  "Everyday Lily",
  "Everything about Best Friend",
  "Ex-girlfriend",
  "Exclusive Contract",
  "Excuse me, This is my Room",
  "Extra Credit",
  "Fallen Flower",
  "Family Business",
  "Fatal Woman",
  "Festival Island",
  "Find Me",
  "Flames",
  "Food Chain",
  "Frequency",
  "Friendly Relationship",
  "From Poker Face to Cumming Face in 90 Seconds",
  "Front House Lily",
  "Fruitless",
  "Fucked the World Tree",
  "Getting to Know Grace",
  "Ghost Love",
  "Girls’ Only",
  "Gluestick Girl",
  "God of App",
  "Gu-Ho’s Escape",
  "Guest House",
  "H-Campus",
  "H-Mate",
  "Hadomae",
  "Hand Play",
  "Hand in Hand",
  "Happy",
  "Hari’s Steamy Boarding House",
  "Healing Hands OBGYN",
  "Her Dirty Thirty Scandal",
  "Her Situation",
  "Her Voice",
  "Herbal Love Story",
  "Hidden Feeling",
  "Him and Him and Him",
  "His Return",
  "Hole in One",
  "Homestay",
  "Honey Bed Talk",
  "Hooked",
  "Household Affairs",
  "Housekeeper",
  "How to Train Her",
  "Hugo",
  "Hunting for Cougars",
  "Hyeonjung's Residence",
  "I Became a Sugar Daddy",
  "I Can’t Stand It, Ajumma",
  "I Ended Up in the World of Murim",
  "I Gave My First Time to My Brother",
  "I Have To Sleep With A Stranger?",
  "I'm The Leader Of A Cult",
  "Illicit Love",
  "Inevitable Trap",
  "Inexperienced",
  "Inside the Uniform",
  "Inside the bus",
  "Intern Haenyeo",
  "Is This The Way that You Do It?",
  "Isekai Fall of the Hero",
  "Island Puzzle",
  "Island Without Shadows",
  "Johnson Contract",
  "Keep it a secret from your mother!",
  "Killing Stalking",
  "Kitsch Year",
  "Lady & Maid",
  "Lady Elisha’s Diary of Debauchery",
  "Lady Garden",
  "Lady Long Legs",
  "Law Of Reincarnation",
  "Leave the Work to Me!",
  "Lesbian Sex Hell",
  "Let it be",
  "Lilith",
  "Live-In Son-in-Law",
  "Living With Two Busty Women",
  "Living With a MILF",
  "Living with A Succubus",
  "Log in to Lust-a-land",
  "Love Factory",
  "Love Is On The Air",
  "Love Me More",
  "Love Parameter",
  "Love Prelude",
  "Loveniverse",
  "MILF Hunting In Another World",
  "Ma'am, it's on SALE!",
  "Magnetic Pull",
  "Maid",
  "Make a Wish",
  "Making My Blackmailer Cum",
  "Malja",
  "Mamitas",
  "Manitto",
  "Married Woman",
  "Masters of Masturbation",
  "Mean Guy",
  "Mia’s Tool",
  "Midnight Breeze",
  "Midnight Taxi",
  "Midsummer Night’s Dream",
  "Miss Mystic",
  "Missing Nine",
  "More Than Friends",
  "Mother And Daughter Next Door",
  "Mother Hunting",
  "Mother-In-Law Bends to My Will",
  "Mother-Son Island Survival",
  "Ms. Master (Aunt’s Secret)",
  "Ms.Stepford",
  "My Aunt",
  "My Best Friend’s Girl",
  "My Body",
  "My Dad’s Girl",
  "My Father’s USB",
  "My First Time is with... My Little Sister!?",
  "My Friend’s Dad",
  "My Friend’s Sister",
  "My Girlfriend is My Stepmother",
  "My Girlfriend is a Star",
  "My Kingdom (Silent War)",
  "My Neighborhood’s Female Teacher",
  "My Secretary’s Got a Secret",
  "My Stepmom",
  "My Stepmom’s Plan",
  "My Sweet Home",
  "My Teacher",
  "My Wife is a Mom",
  "My Wife’s Friend",
  "My Wives",
  "My Worst Lover",
  "My female friend who crossed the line",
  "My girlfriend is a G-Cup!",
  "NEXT Gossip",
  "Naughty Girl",
  "Naughty Positions",
  "Never Too Late",
  "New Employee",
  "New Town",
  "Nineteen",
  "No Goddess, No!",
  "No Holes Barred",
  "No Way Out",
  "No to Obsession, Yes to Love",
  "Nogada Romance",
  "Not Friends",
  "Not One, But Two",
  "Not in School!",
  "Obscene Baguette",
  "Office Ladies",
  "On My Way",
  "One's In-Laws Virgins",
  "Only You",
  "Our Complications",
  "Our Exchange",
  "Overlapping",
  "Panties Fantasy",
  "Park Moojik Hit the Jackpot",
  "Part Time Job",
  "Payment Accepted",
  "Pet Robot Lilly",
  "Please Kill My Husband",
  "Pleasure Chamber",
  "Polyamory",
  "Pregnancy Village",
  "Prison Island",
  "Producer: Trainee",
  "Public Interest",
  "Punishments for Bad Girls",
  "Rabbit Hole",
  "Raw Sex With a Country Gal ~I’ll Show You the Ropes~",
  "Reborn As A Master",
  "Refrain Love",
  "Relationship Reversal",
  "Reporting For Duty Ma’Am",
  "Returning Girlfriend",
  "Reunion",
  "Risque Caller",
  "Run Away",
  "S Diaries 100",
  "S Flower",
  "SEDUCTION : Doll Castle",
  "SStudy",
  "Sadistic Beauty",
  "Safe Haven",
  "Secret Affection",
  "Secret Alliance",
  "Secret Campus",
  "Secret Friend",
  "Secret Neighbors",
  "Secret World of Martial Arts",
  "Secret X Folder",
  "Seduction",
  "Seeing Her Panties Lets Me Stick In",
  "Sergeant Brynn",
  "Set It!",
  "Sex Knights",
  "Sex Note",
  "Sex Stopwatch",
  "Sexy Manga Club",
  "Sexy Virtual Elf",
  "She Is Young",
  "She’s Back",
  "Shh! Her Secret",
  "Shorts",
  "Si-Eun",
  "Siblings",
  "Single Again",
  "Sister In Law (Kim Jol Gu)",
  "Sister-in-law",
  "Slave Knight of the Elf",
  "Sneaked Into A Horny Girls’ School",
  "Sneaky Deal",
  "So close, yet so far",
  "Sold Out Girl",
  "Son of Nam",
  "Sow",
  "Spirit Possession",
  "Sponsor Me Please",
  "Sports Girl",
  "Stand up Guy",
  "Stargram Goddess",
  "Stepmother Friends",
  "Stolen",
  "Stuck in Time",
  "Study Dates",
  "Stupid Love",
  "Succubus System",
  "Sweet Angels",
  "Sweet Guy",
  "THE CHANGE OF SEASON",
  "Talk to Me",
  "Tasty Chat 0km",
  "Teacher Training",
  "Tell Me You Love Me",
  "The Assistant",
  "The BJ Manager Who Boosts His Favorability",
  "The Blood of Madam Giselle",
  "The Cheat Code Hitter Fucks Them All",
  "The Commander's Daughter",
  "The Delivery Man",
  "The Desire to Kill",
  "The Duchess’ Lewd Invitation",
  "The Family Tree",
  "The Fling Zone",
  "The Food Chain",
  "The General Is Here!",
  "The Girl Next Door",
  "The Girl that Wet the Wall",
  "The Good Manager",
  "The Hole Diary",
  "The Ladies’ Associate",
  "The Leash",
  "The Mask: Two Faces",
  "The Men in My Bed",
  "The Naughty Volleyball Team",
  "The Neighborhood Celebrity",
  "The Nice Woman",
  "The Paradise",
  "The Perfect Roommates",
  "The Real Deal",
  "The Repeat Student",
  "The Secret 3P Sleepover in a 7 Square Meter Room",
  "The Secret Affairs Of The 3rd Generation Chaebol",
  "The Sexy Alien Next Door",
  "The Show",
  "The Snow",
  "The Stand-up Guy",
  "The Story of How I Got Together With The Manager On Christmas",
  "The Taste of Money",
  "The Two Newcomers",
  "The Unforeseen Guest",
  "The Unwanted Roommate",
  "The Warrior Became an Academy Professor After Divorce",
  "The Whale",
  "The White Room",
  "The Widow",
  "The Woman Next Door",
  "Thirst",
  "Thirty-two VS Twenty",
  "Three’s a couple",
  "Tie Me Up!",
  "Tissue Guzzler",
  "Tonight",
  "Tonight, You're My Dinner",
  "Tonight, You’re My Dinner",
  "Touch Me",
  "Touching My Older Sister Under the Table",
  "Trophy Wives",
  "Troublesome Sister",
  "Tutoring the Lonely Missus",
  "Twice the Love",
  "Twin Recipe",
  "Two Birds In Spring",
  "Two Wives",
  "Uncle",
  "Under Observation My First Loves and I",
  "Unspeakable",
  "Venus Guytrap",
  "WIFE GAME",
  "Weak Point",
  "Welcome to Kids Cafe",
  "What Does the Fox Say?",
  "What’s Going On?",
  "What’s for Dinner",
  "What’s for Today Dinner?",
  "Where is My Hammer?",
  "Who Cares If I’m a Loser!",
  "Who Did You Do With?",
  "Why Is it You?",
  "Wife Training",
  "Wild Eyes",
  "Will You Do as I Say?",
  "With My Brother’s Friends",
  "Woodman Dyeon",
  "You Can Cum Three More Times, Right?",
  "You Me Her",
  "You Watch Stuff Like That?",
  "You are not that Special!",
  "Young Boss",
  "You’re so Handsome",
  "gomusin",
  "“Hypnotized” Sex with My Brother",
  "“Just The Tip Inside” is Not Sex",
].map(standardiseString);
