const readOrIgnoreWebtoons = [
  "#Dense #Summer #Firstlove",
  "15 Beauties",
  "15 Minutes",
  "150-1 Street",
  "69 University",
  "89193",
  "A Chaste Girl’s Climax at a Nudist Beach",
  "A Crushing Confession",
  "A Different Class",
  "A Gift",
  "A Killer Woman",
  "A Secret Lesson With My Younger Sister",
  "A Sexless Wife Finds Pleasures",
  "A Twisted Day",
  "A Wonderful New World",
  "A World That I Rule",
  "A World of Our Own",
  "A Young Auntie",
  "AMU",
  "Achilles Heel",
  "Adam's Sweet Agony",
  "Aesthetic Predator",
  "After Work Love Affairs",
  "Aharoo",
  "Alice’s Feeling Radio",
  "Alive and Swell",
  "All Night Sex with Biggest Cock",
  "Alt Account Trap!",
  "Amnesia",
  "An Adult’s Experiences",
  "An Innocent Sin",
  "An Introduction to MILFs",
  "Analogue",
  "Anything for You",
  "Aqua",
  "BROTHEL",
  "Back with a Bang",
  "Bad Mom",
  "Bad Parenting",
  "Banging Mother And Daughter",
  "Banging My Aunt",
  "Bastard’s Dead Man",
  "Be Our Guest",
  "Beautiful Days",
  "Beethoven Syndrome",
  "Between Us (Goinmul)",
  "Between Us",
  "Beyond Imagination",
  "Billiard Room Love",
  "Blazing Sun",
  "Block 69",
  "Blood Link",
  "Blooming Sequence",
  "Body Bind",
  "Body Choke",
  "Boss Around",
  "Boss Reverse",
  "Boss! Give me your daughter!",
  "Brawling Go!",
  "Breaking A Romantic Fantasy Villain",
  "Bride Training",
  "Bully Girl",
  "Busted in One Thrust",
  "Butterfly Dream",
  "By Chance",
  "Caffeine",
  "Campus Love",
  "Can I be a Sex Slave, Not a Priest?",
  "Capture",
  "Cartoonists NSFW",
  "Casting",
  "Castle ; Trapped",
  "Cat Fight",
  "Change Wife",
  "Cheater’s Paradise",
  "Cheer Up, Namjoo",
  "Close As Neighbors",
  "Close Family",
  "Club Sodom",
  "Cohabitation with my Ex-Wife",
  "Cohabitation!",
  "Cold? Hot!",
  "Collapse & Rewind",
  "College Grades Skyrocketing",
  "Confidentiality Agreement",
  "Corner Shop",
  "Corruption In The Dungeon",
  "Couple Game: 17 Sex Fantasies Ver.2",
  "Cowgirl’s Riding-Position Makes Me Cum",
  "Creampie",
  "Crime And Punishment",
  "Crossing the Line",
  "DISFARMING",
  "Daddy-in-law",
  "Dangerous Roomies",
  "Dating Contract",
  "Daughter Friend",
  "Daughter In Law",
  "Daydream",
  "Dear Door",
  "Death Angel",
  "Deceit: Snake’s Tongue",
  "Deceptions",
  "Depths of Hell",
  "Depths of Malice",
  "Desire Realization App",
  "Desperate Measures",
  "Deviant Diary",
  "Dirty Reverie",
  "Do You Like to Exercise?",
  "Do You Wanna Fight in This Life, Too?",
  "Don’t Be Like This! Son-In-Law",
  "Don’t Seduce Me!",
  "Dorm Room Sisters",
  "Double Life of Gukbap",
  "Double Trouble",
  "Drama in the Office",
  "Dreaming : My Friend’s Girl",
  "Drug Candy",
  "Drunk and Wet",
  "Dual Residence",
  "Dumped",
  "E Romance",
  "Ecstasy Hearts",
  "Elixir",
  "Emergency Stairs",
  "Escape Loser",
  "Everyday Lily",
  "Everything about Best Friend",
  "Ex-girlfriend",
  "Exclusive Contract",
  "Excuse me, This is my Room",
  "Extra Credit",
  "Extreme Life of a Teenager",
  "Fallen Flower",
  "Family Business",
  "Fatal Woman",
  "Festival Island",
  "Find Me",
  "Finding Assistant Manager Kim",
  "Flames",
  "Food Chain",
  "For Sale: Fallen Lady, Never Used",
  "For Your Happiness",
  "Frequency",
  "Freshman Yulmoo’s Club Life",
  "Friendly Relationship",
  "From Poker Face to Cumming Face in 90 Seconds",
  "Front House Lily",
  "Fruitless",
  "Fucked the World Tree",
  "Fucking My Niece at the Girls' Pajama Party",
  "Galewind Murim Tales",
  "Getting to Know Grace",
  "Ghost Love",
  "Girls’ Only",
  "Global Sexual Culture Research Institute",
  "Gluestick Girl",
  "God of App",
  "Good Night",
  "Gu-Ho’s Escape",
  "Guest House",
  "H-Campus",
  "H-Mate",
  "Hadomae",
  "Hahri's Lumpy Star",
  "Hand Play",
  "Hand in Hand",
  "Happy",
  "Harem King",
  "Hari’s Steamy Boarding House",
  "Healing Hands OBGYN",
  "Her Dirty Thirty Scandal",
  "Her Nickname is…",
  "Her Shim-Cheong",
  "Her Situation",
  "Her Toys",
  "Her Voice",
  "Herbal Love Story",
  "Hidden Feeling",
  "Him and Him and Him",
  "His Return",
  "His Women's University",
  "Hole in One",
  "Homestay",
  "Honey Bed Talk",
  "Hooked",
  "Hospitalized Life in Another World",
  "Host Club",
  "Hot Sex in the Winter",
  "Household Affairs",
  "Housekeeper",
  "How to Train Her",
  "Hubby Bunny",
  "Hugo",
  "Humans from another world",
  "Hunting for Cougars",
  "Hyeonjung's Residence",
  "Hypnotist Security Guard",
  "I Became a Sugar Daddy",
  "I Can’t Stand It, Ajumma",
  "I Ended Up in the World of Murim",
  "I Gave My First Time to My Brother",
  "I Have To Sleep With A Stranger?",
  "I'm The Leader Of A Cult",
  "Idol Manager",
  "If I Say No, You’re Still Gonna Put It In, Right?",
  "Illicit Love",
  "Inevitable Trap",
  "Inexperienced",
  "Inside the Uniform",
  "Inside the bus",
  "Intern Haenyeo",
  "Is This The Way that You Do It?",
  "Isekai Dragondick Knight Commander",
  "Isekai Fall of the Hero",
  "Island Puzzle",
  "Island Without Shadows",
  "Johnson Contract",
  "Kangcheol’s Bosses",
  "Keep it a secret from your mother!",
  "Killing Stalking",
  "Kitsch Year",
  "Lady & Maid",
  "Lady Elisha’s Diary of Debauchery",
  "Lady Garden",
  "Lady Long Legs",
  "Law Of Reincarnation",
  "Leave the Work to Me!",
  "Lesbian Sex Hell",
  "Let it be",
  "Lilith",
  "Live-In Son-in-Law",
  "Living With Two Busty Women",
  "Living With a MILF",
  "Living with A Succubus",
  "Log in to Lust-a-land",
  "Love Chair Lab",
  "Love Factory",
  "Love Is On The Air",
  "Love Me More",
  "Love Parameter",
  "Love Prelude",
  "Love Theme Park",
  "Loveniverse",
  "MILF Hunting In Another World",
  "Ma'am, it's on SALE!",
  "Magnetic Pull",
  "Maid",
  "Make a Wish",
  "Making My Blackmailer Cum",
  "Malja",
  "Mamitas",
  "Manitto",
  "Married Woman",
  "Marry Me, I'll Fuck You Until You're Pregnant!",
  "Masters of Masturbation",
  "Mean Guy",
  "Meat Doll Workshop in Another World",
  "Mia’s Tool",
  "Midnight Breeze",
  "Midnight Taxi",
  "Midsummer Night’s Dream",
  "Milf Guard",
  "Miss Mystic",
  "Missing Nine",
  "More Than Friends",
  "Mother And Daughter Next Door",
  "Mother Hunting",
  "Mother, I’m Sorry",
  "Mother-In-Law Bends to My Will",
  "Mother-Son Island Survival",
  "Ms. Master (Aunt’s Secret)",
  "Ms.Stepford",
  "Musical Chairs ~I Accidentally Sat on His Dick~",
  "My Aunt",
  "My Best Friend’s Girl",
  "My Body",
  "My Dad’s Girl",
  "My Enemy Is My First Love",
  "My Father’s USB",
  "My First Time is with... My Little Sister!?",
  "My Friend’s Dad",
  "My Friend’s Sister",
  "My Girlfriend is My Stepmother",
  "My Girlfriend is a Star",
  "My Illustrator",
  "My Kingdom (Silent War)",
  "My Landlady Noona",
  "My Neighborhood’s Female Teacher",
  "My Other Girlfriend",
  "My Pillow Business Begins!",
  "My Secretary’s Got a Secret",
  "My Special Squishy Someone",
  "My Stepmom",
  "My Stepmom’s Plan",
  "My Study Method",
  "My Swimsuit Slipped... and It Went In!?",
  "My Teacher",
  "My Wife is a Mom",
  "My Wife’s Friend",
  "My Wives",
  "My Worst Lover",
  "My female friend who crossed the line",
  "My girlfriend is a G-Cup!",
  "NEXT Gossip",
  "Naughty Girl",
  "Naughty Positions",
  "Neighbors",
  "Never Too Late",
  "New Employee",
  "New Town",
  "Night Hospital",
  "Nineteen",
  "No Goddess, No!",
  "No Holes Barred",
  "No Way Out",
  "No to Obsession, Yes to Love",
  "Nogada Romance",
  "Not Friends",
  "Not One, But Two",
  "Not in School!",
  "Obscene Baguette",
  "Observation Diary",
  "Office Ladies",
  "On My Way",
  "One's In-Laws Virgins",
  "Only You",
  "Our Complications",
  "Our Exchange",
  "Our Kinky Newlywed Life",
  "Our Secret Garden",
  "Overlapping",
  "Panties Fantasy",
  "Panty Note",
  "Park Moojik Hit the Jackpot",
  "Part Time Job",
  "Payment Accepted",
  "Pervert Club",
  "Pet Robot Lilly",
  "Phantom Sex King",
  "Playing a game with my Busty Manager",
  "Please Have a Meal",
  "Please Kill My Husband",
  "Pleasure Chamber",
  "Polyamory",
  "Pregnancy Village",
  "Prison Island",
  "Producer: Trainee",
  "Public Interest",
  "Punishments for Bad Girls",
  "Pure Love",
  "Queen Bee",
  "Rabbit Hole",
  "Raw Sex With a Country Gal ~I’ll Show You the Ropes~",
  "Reborn As A Master",
  "Reborn with Big Rizz Energy",
  "Reborn with a big dick!",
  "Refrain Love",
  "Relationship Reversal",
  "Rental Girls",
  "Rented Room Brides",
  "Reporting For Duty Ma’Am",
  "Returning Girlfriend",
  "Reunion",
  "Risque Caller",
  "Run Away",
  "Running Man",
  "S Diaries 100",
  "S Flower",
  "SEDUCTION : Doll Castle",
  "SStudy",
  "Sadistic Beauty",
  "Safe Haven",
  "Secret Affection",
  "Secret Alliance",
  "Secret Campus",
  "Secret Friend",
  "Secret Neighbors",
  "Secret Siblings 2",
  "Secret World of Martial Arts",
  "Secret X Folder",
  "Secret! Orgasm Hero",
  "Seduction",
  "Seeing Her Panties Lets Me Stick In",
  "Sergeant Brynn",
  "Set It!",
  "Sex Knights",
  "Sex Note",
  "Sex Stopwatch",
  "Sex for Survival",
  "Sexual Guidance Officer",
  "Sexy Manga Club",
  "Sexy Times With My Tiny Childhood Friend",
  "Sexy Virtual Elf",
  "She Is Young 2",
  "She Is Young",
  "She’s Back",
  "Shh! Her Secret",
  "Shimiken",
  "Shorts",
  "Si-Eun",
  "Siblings",
  "Single Again",
  "Sister In Law (Kim Jol Gu)",
  "Sister-in-law",
  "Slave Knight of the Elf",
  "Sleeping Niece, Sneaky Uncle.",
  "Sneaked Into A Horny Girls’ School",
  "Sneaky Deal",
  "So close, yet so far",
  "Soeun",
  "Sold Out Girl",
  "Son of Nam",
  "Sorcery Tales: A Yokai Harem",
  "Sow",
  "Spirit Possession",
  "Sponsor Me Please",
  "Sports Girl",
  "Stand up Guy",
  "Stargram Goddess",
  "Stepmother Friends",
  "Stolen",
  "Stuck in Time",
  "Study Dates",
  "Stupid Love",
  "Succubus System",
  "Sultan's Love",
  "Superhuman Battlefield",
  "Superstitious Nine",
  "Sweet Angels",
  "Sweet Guy",
  "THE CHANGE OF SEASON",
  "Talk to Me",
  "Taming Females to Rise in Status",
  "Tasty Chat 0km",
  "Teacher Training",
  "Teaching Sex to My Amnesiac Sister",
  "Tell Me You Love Me",
  "The Assistant",
  "The BJ Manager Who Boosts His Favorability",
  "The Blood of Madam Giselle",
  "The CEO’s Dog Collar",
  "The Cheat Code Hitter Fucks Them All",
  "The Commander's Daughter",
  "The Dark Mage’s Return to Enlistment",
  "The Delivery Man",
  "The Descent of the Demonic Master",
  "The Desire to Kill",
  "The Duchess’ Lewd Invitation",
  "The Family Tree",
  "The Fling Zone",
  "The Food Chain",
  "The Game: Fatal Doctor",
  "The General Is Here!",
  "The Girl Next Door",
  "The Girl that Wet the Wall",
  "The Giving Girl",
  "The Good Manager",
  "The Heart of Red Cloak",
  "The Hole Diary",
  "The Iron-Wall Beauty of My Department is a Masochist?!",
  "The Ladies’ Associate",
  "The Leash",
  "The Love Meowtchmaker",
  "The Man Who Devours",
  "The Mask: Two Faces",
  "The Men in My Bed",
  "The Naughty Volleyball Team",
  "The Neighborhood Celebrity",
  "The Nice Woman",
  "The Paradise",
  "The Perfect Roommates",
  "The Real Deal",
  "The Repeat Student",
  "The Secret 3P Sleepover in a 7 Square Meter Room",
  "The Secret Affairs Of The 3rd Generation Chaebol",
  "The Sexy Alien Next Door",
  "The Show",
  "The Snow",
  "The Stand-up Guy",
  "The Story of How I Got Together With The Manager On Christmas",
  "The Taste of Money",
  "The Two Newcomers",
  "The Unforeseen Guest",
  "The Unwanted Roommate",
  "The V Squad",
  "The Warrior Became an Academy Professor After Divorce",
  "The Whale",
  "The White Room",
  "The Widow",
  "The Woman Next Door",
  "Thirst",
  "Thirty-two VS Twenty",
  "This Shithole Company is Mine Now!",
  "Three’s a couple",
  "Tie Me Up!",
  "Tissue Guzzler",
  "Tonight",
  "Tonight, You're My Dinner",
  "Tonight, You’re My Dinner",
  "Touch Me",
  "Touching My Older Sister Under the Table",
  "Town Girls",
  "Traditional Job of Washing Girls' Body",
  "Trophy Wives",
  "Troublesome Sister",
  "Tutoring the Lonely Missus",
  "Twice the Love",
  "Twin Recipe",
  "Two Birds In Spring",
  "Two Wives",
  "Uncle",
  "Under Observation My First Loves and I",
  "Unspeakable",
  "Vanishing Twin",
  "Venus Guytrap",
  "WIFE GAME",
  "Weak Point",
  "Welcome to Kids Cafe",
  "Wet Women",
  "What Does the Fox Say?",
  "What Happened at the Hypnosis Massage Shop",
  "What’s Going On?",
  "What’s for Dinner",
  "What’s for Today Dinner?",
  "Where is My Hammer?",
  "Where the Heart Is",
  "Who Cares If I’m a Loser!",
  "Who Did You Do With?",
  "Why Is it You?",
  "Wife Training",
  "Wife for 1000 Days",
  "Wild Eyes",
  "Will You Do as I Say?",
  "Winter short story: Merry Sex Friends",
  "With My Brother’s Friends",
  "Women of God",
  "Woodman Dyeon",
  "Yeoju and Haru",
  "You Came During the Massage Earlier, Didn’t You?",
  "You Can Cum Three More Times, Right?",
  "You Cum, You Lose! – Wrestling with a Pervert",
  "You Me Her",
  "You Watch Stuff Like That?",
  "You are not that Special!",
  "You'll Cum in Less Than a Minute!",
  "Young Boss",
  "Your Creepy Bucketlist",
  "You’re so Handsome",
  "[Dating Sim Short Story] The Dating Simulator Cheat Code",
  "gomusin",
  "“Hypnotized” Sex with My Brother",
  "“Just The Tip Inside” is Not Sex",
].map(standardiseString);
